-- 1. නිෂ්පාදන පින්තූර (Images) උඩුගත කිරීමට අවශ්‍ය අවසර ලබා දීම
create policy "Public Access" on storage.objects for all to anon using ( bucket_id = 'product-images' );

-- 2. ඇණවුම් (Orders) සඳහා අවශ්‍ය Table එක නිර්මාණය කිරීම
create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    customer_name text not null,
    customer_phone text not null,
    customer_address text not null,
    items text not null,
    total numeric not null,
    status text default 'Pending Payment'::text
);

-- 3. ඕනෑම අයෙකුට ඇණවුමක් ඇතුළත් කිරීමට (Insert) අවසර දීම
create policy "Enable insert for all users" on public.orders for insert with check (true);

-- 4. ඕනෑම අයෙකුට ඇණවුම් බැලීමට (Read) සහ යාවත්කාලීන කිරීමට (Update) අවසර දීම (Demo එක සඳහා)
create policy "Enable read for all users" on public.orders for select using (true);
create policy "Enable update for all users" on public.orders for update using (true);

-- 5. නිෂ්පාදන (Products) සඳහාද සියලු අවසර ලබා දීම
create policy "Enable all for products" on public.products for all using (true);

-- වැදගත්: මෙම SQL එක Supabase Dashboard එකේ SQL Editor එකට කොපි කර "Run" කරන්න.
